### ISSUE TITLE
Constrain values for diagnosis

### ISSUE THREAD

**Issue by kelshmo** [cw-dvr8/JSON-validation-schemas#10]
Do we restrict values for [`primaryDiagnosis`](https://github.com/cw-dvr8/JSON-validation-schemas/blob/408a80e6cc95d9ceb70c834a9cd012da29d106f1/validation_schemas/reference_definitions/clinicalData.json#L508)?

**Comment by cw-dvr8** [comment]
Not currently.

**Comment by kelshmo** [comment]
Is there a reason we don't build on this [diagnosis ontology](https://github.com/Sage-Bionetworks/synapseAnnotations/blob/5c2d86d6462b69378969976fc7dcc0e2f3b09b87/synapseAnnotations/data/experimentalData.json#L1554)?

**Comment by cw-dvr8** [comment]
We do.  primaryDiagnosis has a remote reference to this key in synapseAnnotations.  I misunderstood, I thought you were asking if we were restricting the diagnosis to only the ones that would apply to PsychENCODE.

**Comment by kelshmo** [comment]
Ok great!
