### ISSUE TITLE
move boolean conversion functions into library module

### ISSUE THREAD

**Issue by kdaily** [cw-dvr8/JSON-validation-schemas#2]

**Comment by kdaily** [comment]
`convert_to_boolean` and `convert_from_boolean` in `validate_using_schema.py`

**Comment by cw-dvr8** [comment]
- Removed the conversion functions from validate_using_schema.py

- Renamed convert_to_boolean to convert_string_to_other and reworked it such that it can convert a string to either a Boolean or a numeric, and added it to schema_tools.py

- Renamed convert_from_boolean to convert_from_other and reworked it such that it can convert Booleans and numerics to strings, and added it to schema_tools.py
