### ISSUE TITLE
document what errors in schemas have a 'properties' value

### ISSUE THREAD

**Issue by kdaily** [cw-dvr8/JSON-validation-schemas#4]
The `validate_object` function checks if the schema path object has a `properties` value. Document which types of errors have this and which don't.

**Comment by cw-dvr8** [comment]
Done.

**Comment by kdaily** [comment]
The notes look good, but move them inside the docstring for the function instead so we can see them when getting help for the function.

**Comment by cw-dvr8** [comment]
Comments have been moved.
