### ISSUE TITLE
evaluate using openpyexcel to output as csv

### ISSUE THREAD

**Issue by kdaily** [cw-dvr8/JSON-validation-schemas#8]
Could you build all of the worksheets and then just output to CSV? That would remove code to generate CSV separately.

**Comment by cw-dvr8** [comment]
openpyxl doesn't have the capability of writing to csv files.  However, pandas has the capability of writing both csv files and Excel workbooks, so I modified the code such that there is a single driver program that the user passes a parameter into specifying the type of output, and the program calls a format-specific function to generate the template.
